### ISSUE TITLE
processes of mystem still alive

### ISSUE THREAD

**Issue by thegraal** [Digsolab/pymystem3#4]
I use .lemmatize() in many threads(those threading.Thread)
There are some "..bin/mystem --format json -gi -d -c" still alive after my threads are finished.
Look at pic to keep it clear
![screenshot at 00-54-08](https://cloud.githubusercontent.com/assets/9771189/6927930/10b2c5b8-d80a-11e4-8681-8c4dfb4ca59b.png)
is there a way to finish these processes? it consumes large amount of memory after few work days

**Comment by alexanderpanchenko** [comment]
hello, 

we will look into the problem. if you find the solution yourself, please do not hesitate to make a pull request

**Comment by neglectedvalue** [comment]
We could provide Mystem.close method to shutdown the mystem process.

**Comment by neglectedvalue** [comment]
In pymystem3-0.1.4, the method Mystem.close is available.
