### ISSUE TITLE
Enable pipepline mode for pypy

### ISSUE THREAD

**Issue by lopuhin** [Digsolab/pymystem3#5]
Right now pipeline mode is disabled for pypy, but it works at least for PyPy 2.5.1. Can it be turned on, either based on version number, or on feature detection? I can check what was wrong on pypy 1.9

**Comment by alexanderpanchenko** [comment]
Hello, we are currently busy addressing one issue related to windows platform. If you will be able to provide a pull request with a fix we it would be amazing. We have some basic tests with pypy on Trevis CI. Please check the version used there.

**Comment by neglectedvalue** [comment]
The problem was with PyPy <2.5.0. Due to an unknown bug the method select.select always exits with timeout. In pymystem3-0.1.4, I check version of PyPy and enable pipeline mode if PyPy >=2.5.1 is using. Thanks for the report!

**Comment by lopuhin** [comment]
Thank you! Sorry that I did not turn up to do it. Just had a quick look at that patch, I think that here https://github.com/Digsolab/pymystem3/compare/master...neglectedvalue:master#diff-e14f3860ac8eded53e5a95872911d3bdR47 should also be a POSIX check, otherwise pipeline mode will be "on" for pypy on windows.

**Comment by neglectedvalue** [comment]
Yeah, right.

**Comment by neglectedvalue** [comment]
Commit https://github.com/neglectedvalue/pymystem3/commit/c2d58a39b68a495abe25a8fad3399da409b35be4
Released as 0.1.5
